sudo: false
language: ruby
rvm:
  - 2.4.1
gemfile: "gems.rb"
before_script:
  - "ruby lib/initial_setup.rb ../.travis_setup"
  - "mysql -e 'create database training_grant_test;'"
  - "rails db:migrate"
